# Generated by Django 5.2 on 2025-04-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='password',
            field=models.CharField(default='', help_text='Password used to encrypt this PDF', max_length=50),
            preserve_default=False,
        ),
    ]
